version: "3"
services:
  local-db:
    image: mariadb:latest
    container_name: mariadb_springboot
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: 1234
      TZ: Asia/Seoul
    volumes:
      - ./db/mysql/data:/var/lib/mariadb
      - ./db/mysql/init:/docker-entrypoint-initdb.d
    platform: linux/x86_64